- name: copy
  ansible.builtin.copy:
    src: ./files/cp/directpv.sh
    dest: /tmp/directpv.sh
    mode: "0755"

- name: copy
  ansible.builtin.copy:
    src: ./files/cp/seccomp.json
    dest: /tmp/seccomp.json
    mode: "0755"

- name: lineinfile ~/.bashrc
  ansible.builtin.lineinfile:
    path: ~/.bashrc
    line: 'export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"'

# 3回実行する（一発で上手くいかない場合があるため）
# ref: https://github.com/minio/directpv/blob/master/docs/installation.md
# ref: https://github.com/minio/directpv/blob/master/seccomp.json
- name: shell directpv
  ansible.builtin.shell: /tmp/directpv.sh
  environment:
    PATH: "{{ ansible_env.HOME }}/.krew/bin:{{ ansible_env.PATH }}"
  args:
    chdir: /tmp
    executable: /bin/bash
  register: result
  ignore_errors: true
- name: Show stdout for all iterations
  debug:
    msg: "{{ result.stdout_lines }}"
