- name: all
  hosts: all
  remote_user: "{{ USER }}"
  become: true
  vars_files:
    - ./vars_files/env.yml
    - ./vars_files/vars.yml
  tasks:
    - include_tasks: "./tasks/{{ item }}"
      with_items: "{{ variables.all }}"
      when: variables.all

- name: lb
  hosts: lb
  remote_user: "{{ USER }}"
  become: true
  vars_files:
    - ./vars_files/env.yml
    - ./vars_files/vars.yml
  tasks:
    - include_tasks: "./tasks/{{ item }}"
      with_items: "{{ variables.lb }}"
      when: variables.lb

- name: all-node
  hosts: all_node
  remote_user: "{{ USER }}"
  become: true
  vars_files:
    - ./vars_files/env.yml
    - ./vars_files/vars.yml
  tasks:
    - include_tasks: "./tasks/{{ item }}"
      with_items: "{{ variables.k8s.all_node }}"
      when: variables.k8s.all_node

- name: cp
  hosts: cp
  remote_user: "{{ USER }}"
  become: true
  vars_files:
    - ./vars_files/env.yml
    - ./vars_files/vars.yml
  tasks:
    - include_tasks: "./tasks/{{ item }}"
      with_items: "{{ variables.k8s.cp }}"
      when: variables.k8s.cp

- name: cp-join
  hosts: cp_join
  remote_user: "{{ USER }}"
  become: true
  vars_files:
    - ./vars_files/env.yml
    - ./vars_files/vars.yml
  tasks:
    - include_tasks: "./tasks/{{ item }}"
      with_items: "{{ variables.k8s.cp_join }}"
      when: variables.k8s.cp_join

- name: worker
  hosts: worker
  remote_user: "{{ USER }}"
  become: true
  vars_files:
    - ./vars_files/env.yml
    - ./vars_files/vars.yml
  tasks:
    - include_tasks: "./tasks/{{ item }}"
      with_items: "{{ variables.k8s.worker }}"
      when: variables.k8s.worker

- name: cp-after
  hosts: cp
  remote_user: "{{ USER }}"
  become: false
  vars_files:
    - ./vars_files/env.yml
    - ./vars_files/vars.yml
  tasks:
    - include_tasks: "./tasks/{{ item }}"
      with_items: "{{ variables.k8s.cp_after }}"
      when: variables.k8s.cp_after
